import Head from "next/head";
import { useState } from "react";
import { api } from "@/utils/api";
import { revalidatePath } from "next/cache";


export default function Home() {

  const posts = api.post.getAll.useQuery().data
  const [post, setPost] = useState("")

  const { mutate } = api.post.create.useMutation()

  if (!posts) {
    return <div>loading...</div>
  }

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    const newPost = mutate({ name: post })
    console.log(newPost)
    setPost("")
    // display updated all posts

  }

  return (
    <>
      <Head>
        <title>NFC-Ticket</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={handleSubmit}>
          <label htmlFor="eventName">Event Name</label>
          <input type="text" id="eventName" value={post} onChange={(e) => setPost(e.target.value)} />
          <button type="submit">Create Event</button>
        </form>
        <div>
          {
            posts.map((post) => (
              <div key={post.id}>
                <h1>{post.name}</h1>
              </div>
            ))
          }
        </div>
      </main>
    </>
  );
}