import Head from "next/head";
import { useState } from "react";

export default function Home() {

  const [eventName, setEventName] = useState("")

  return (
    <>
      <Head>
        <title>NFC-Ticket</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        NFC-Ticket!!!
      </main>
    </>
  );
}