import Head from "next/head";
import { GetServerSidePropsContext, InferGetServerSidePropsType } from "next";
import { useUser } from "@clerk/nextjs";
import Link from "next/link";


export default function Home() {

  const { user, isSignedIn } = useUser()

  if (!isSignedIn) return <div>Not signed in</div>

  return (
    <>
      <Head>
        <title>NFC-Ticket</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home</h1>
        <p className="">You are: {user.firstName}</p>
        <div className="flex gap-4">

          <Link href="/admin">Admin</Link>
          <Link href="/event">Events</Link>
        </div>
      </main>
    </>
  )

}
